### ISSUE TITLE
Client basic ops QA

### ISSUE THREAD

**Issue by shmuel-raichman** [moti-malka/Willy#35]
👍 good job I like it.

Here are a few things to consider. 
Bugs:
- UI Not refreshing after basic-ops.
- UI hang after error trying to remove non existing conatiner.

Enhancements:
- Entire line should open details page.
- Show mount path insted of int.

Suggestions:
- bulk ops, make operation for few containers at once.

**Comment by moti-malka** [comment]
Fixed on v1
