### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by shmuel-raichman** [moti-malka/Willy#40]
* Sometimes operation break the UI and I can't get list of containers anymore. <br>
Not sure when exacly but here some that i noticed:
  - closing logs windows.
  - running container ? maybe missing conatiner

* Refresh 
Whem I'm refreshing the page i'm getting 404

* Errors
When backend return an error (500) UI carshing a bit and not explaining the issue.
Example: trying to retart container that using port that alreay bind ti diffrent container.

* Logs
When openning logs for some containers (e.g. logza.io container) 
logs are spreated by single character per line.

My guess is that there is some special character in the logs that break it.

@moti-malka the UI need to response at all times, if there is an error then give an error page or in page error.

**Comment by moti-malka** [comment]
Fixed on v1
